# Generated by Django 4.2.4 on 2023-10-12 14:19

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTML/CSS', 'HTML/CSS'), ('JS', 'JS'), ('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO')], db_index=True, default='HTML/CSS', max_length=10, verbose_name='Какой курс')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тема')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.category', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created', 'title'],
            },
        ),
    ]
