# Generated by Django 4.2.4 on 2023-11-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_category_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
